### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by IceRob** [zyl123456aB/SPSG_attack#3]
While attempting to train the model using the following commands: `python SPSG/adversary/transfer.py random models/victim/cubs200-resnet34 \
        --out_dir models/adversary/ADV_DIR --budget 5000 \
        --queryset CUBS200 --batch_size 8 -d

python SPSG/adversary/train.py models/adversary/ADV_DIR models/victim/cubs200-resnet34 \
        resnet34 CUBS200 --budgets 5000 -d 1 --pretrained imagenet \
        --log-interval 100 --epochs 200 --lr 0.01 `, I encountered the following error, causing the process to fail: `Traceback (most recent call last):
  File "SPSG/adversary/train.py", line 215, in <module>
    main()
  File "SPSG/adversary/train.py", line 205, in main
    checkpoint_suffix=checkpoint_suffix, device=device, optimizer=optimizer, **params)
  File "/home/iceboy/SPSG_attack/SPSG/utils/model.py", line 355, in train_model
    log_interval=log_interval)
  File "/home/iceboy/SPSG_attack/SPSG/utils/model.py", line 85, in train_step
    sgs.append(real_targets[2])
IndexError: tuple index out of range`, I would appreciate guidance on how to resolve this issue. It appears the error stems from attempting to access an index in real_targets that does not exist. Any insights on potential fixes or adjustments would be highly helpful.

**Comment by Ma-Ruinan** [comment]
@IceRob Hi, have you solved this problem? I have the same problem.

**Comment by Ma-Ruinan** [comment]
@zyl123456aB Hi, could you please help me solve this problem?

**Comment by IceRob** [comment]
> [@IceRob](https://github.com/IceRob) Hi, have you solved this problem? I have the same problem.

I did't solve it, but i think the problem comes from the wrong shape of the real_targets
